version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd profebot-ia
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target ..
      - cd ..
      - cd target
      - mv profebot-ia-0.0.1-SNAPSHOT.jar application.jar
      - cp application.jar ..
artifacts:
  files:
    - application.jar